export const GET_TOPICLIST_SIDEBAR = {
  REQUEST: "REQUEST_GET_TOPICLIST_SIDEBAR",
  SUCCESS: "SUCCESS_GET_TOPICLIST_SIDEBAR",
  FAILURE: "FAILURE_GET_TOPICLIST_SIDEBAR",
} as const;

export const GET_DETAIL_TOPICPOSTING = {
  REQUEST: "REQUEST_GET_DETAIL_TOPICPOSTING",
  SUCCESS: "SUCCESS_GET_DETAIL_TOPICPOSTING",
  FAILURE: "FAILURE_GET_DETAIL_TOPICPOSTING",
} as const;

export const GET_DETAIL_SUBTOPICPOSTING = {
  REQUEST: "REQUEST_GET_DETAIL_SUBTOPICPOSTING",
  SUCCESS: "SUCCESS_GET_DETAIL_SUBTOPICPOSTING",
  FAILURE: "FAILURE_GET_DETAIL_SUBTOPICPOSTING",
} as const;

export const GET_TOPIC_POSTING = {
  REQUEST: "REQUEST_GET_TOPIC_POSTING",
  SUCCESS: "SUCCESS_GET_TOPIC_POSTING",
  FAILURE: "FAILURE_GET_TOPIC_POSTING",
} as const;

export const GET_SUBTOPIC_POSTING = {
  REQUEST: "REQUEST_GET_SUBTOPIC_POSTING",
  SUCCESS: "SUCCESS_GET_SUBTOPIC_POSTING",
  FAILURE: "FAILURE_GET_SUBTOPIC_POSTING",
} as const;

export const GET_ALL_POSTING = {
  REQUEST: "REQUEST_GET_ALL_POSTING",
  SUCCESS: "SUCCESS_GET_ALL_POSTING",
  FAILURE: "FAILURE_GET_ALL_POSTING",
} as const;
export const WRIRTE_POSTING = {
  REQUEST: "REQUEST_WRIRTE_POSTING",
  SUCCESS: "SUCCESS_WRIRTE_POSTING",
  FAILURE: "FAILURE_WRIRTE_POSTING",
} as const;

export const WRITE_TOPIC = {
  REQUEST: "REQUEST_WRITE_TOPIC",
  SUCCESS: "SUCCESS_WRITE_TOPIC",
  FAILURE: "FAILURE_WRITE_TOPIC",
} as const;

export const WRITE_SUBTOPIC = {
  REQUEST: "REQUEST_WRITE_SUBTOPIC",
  SUCCESS: "SUCCESS_WRITE_SUBTOPIC",
  FAILURE: "FAILURE_WRITE_SUBTOPIC",
} as const;
